[package]
name = "archivum-core"
version = "0.1.0"
edition = "2024"

[dependencies]
crdts = "7.3.2"
serde = { version = "1.0", features = ["derive"] }
uuid = { version = "1.17.0", features = ["v4", "serde"] }
